app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# For logout
logout:
    path: /chapter15/logout

# importer d'autres fichiers 
# resource: '@AcmeOtherBundle/Resources/config/routing.yml'

# ajouter un prefixe /prefix/mon/url
# prefix: /site