app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# For logout
logout:
    path: /chapter15/logout

# For local
#contact:
#  path: /{_locale}/contact
#  defaults: { _controller: AppBundle:Contact:index }
#  requirements:
#    _locale: en|fr|de

# importer d'autres fichiers 
# resource: '@AcmeOtherBundle/Resources/config/routing.yml'

# ajouter un prefixe /prefix/mon/url
# prefix: /site