# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Must be before main
        security_area:
              pattern: ^/chapter15
              http_basic: ~

              logout:
                  invalidate_session: true
                  path: /chapter15/logout
                  target: /

        main:
            anonymous: true
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html




    access_control:
            # require ROLE_ADMIN for /chapter15/admin*
            - { path: ^/chapter15/admin, roles: ROLE_ADMIN }

    # hardcoded users
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            # HWIOAuthBundle for Google, Facebook and Twitter
            in_memory:
                memory:
                    users:
                        ryan:
                              password: ryanpass
                              roles: 'ROLE_USER'
                        admin:
                              password: $2y$12$whsykj6uCdWyQvwF1qTTveZLgCTIIlg/G3Woy/8P5OuQvn2nTdQQW # password = root
                              roles: 'ROLE_ADMIN'

    encoders:
          #Symfony\Component\Security\Core\User\User: plaintext
          Symfony\Component\Security\Core\User\User:
                  algorithm: bcrypt
                  cost: 12


